/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GameGameIdRouteImport } from './routes/game.$gameId'
import { Route as AuthSigninRouteImport } from './routes/auth/signin'
import { Route as AuthErrorRouteImport } from './routes/auth/error'
import { Route as ApiGameRouteImport } from './routes/api/game'
import { Route as ApiAuthProviderRouteImport } from './routes/api/auth.$provider'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GameGameIdRoute = GameGameIdRouteImport.update({
  id: '/game/$gameId',
  path: '/game/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/auth/signin',
  path: '/auth/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthErrorRoute = AuthErrorRouteImport.update({
  id: '/auth/error',
  path: '/auth/error',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGameRoute = ApiGameRouteImport.update({
  id: '/api/game',
  path: '/api/game',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthProviderRoute = ApiAuthProviderRouteImport.update({
  id: '/api/auth/$provider',
  path: '/api/auth/$provider',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/api/game': typeof ApiGameRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/signin': typeof AuthSigninRoute
  '/game/$gameId': typeof GameGameIdRoute
  '/api/auth/$provider': typeof ApiAuthProviderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/api/game': typeof ApiGameRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/signin': typeof AuthSigninRoute
  '/game/$gameId': typeof GameGameIdRoute
  '/api/auth/$provider': typeof ApiAuthProviderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/api/game': typeof ApiGameRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/signin': typeof AuthSigninRoute
  '/game/$gameId': typeof GameGameIdRoute
  '/api/auth/$provider': typeof ApiAuthProviderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/unauthorized'
    | '/api/game'
    | '/auth/error'
    | '/auth/signin'
    | '/game/$gameId'
    | '/api/auth/$provider'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/unauthorized'
    | '/api/game'
    | '/auth/error'
    | '/auth/signin'
    | '/game/$gameId'
    | '/api/auth/$provider'
  id:
    | '__root__'
    | '/'
    | '/unauthorized'
    | '/api/game'
    | '/auth/error'
    | '/auth/signin'
    | '/game/$gameId'
    | '/api/auth/$provider'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  ApiGameRoute: typeof ApiGameRoute
  AuthErrorRoute: typeof AuthErrorRoute
  AuthSigninRoute: typeof AuthSigninRoute
  GameGameIdRoute: typeof GameGameIdRoute
  ApiAuthProviderRoute: typeof ApiAuthProviderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$gameId': {
      id: '/game/$gameId'
      path: '/game/$gameId'
      fullPath: '/game/$gameId'
      preLoaderRoute: typeof GameGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/auth/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/error': {
      id: '/auth/error'
      path: '/auth/error'
      fullPath: '/auth/error'
      preLoaderRoute: typeof AuthErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/game': {
      id: '/api/game'
      path: '/api/game'
      fullPath: '/api/game'
      preLoaderRoute: typeof ApiGameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$provider': {
      id: '/api/auth/$provider'
      path: '/api/auth/$provider'
      fullPath: '/api/auth/$provider'
      preLoaderRoute: typeof ApiAuthProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  ApiGameRoute: ApiGameRoute,
  AuthErrorRoute: AuthErrorRoute,
  AuthSigninRoute: AuthSigninRoute,
  GameGameIdRoute: GameGameIdRoute,
  ApiAuthProviderRoute: ApiAuthProviderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
